plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://bmclapi2.bangbang93.com/maven' }
    flatDir { dirs 'libs' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    
    // 使用本地 libs 目录下的 jar 包
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") { expand "version": project.version }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}

java {
    withSourcesJar()
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}